"""Portable offline Gaia/DAGT public layer."""

from .agents import (
    AgentParseError,
    AgentUnavailableError,
    CacheCorruptionError,
    predictive_text_agent,
    supervisory_qc_agent,
    agent_unavailable,
    load_cached_agent_evidence,
    parse_api_payload,
    require_api_key,
)
from .adapter import GaiaDAGTAdapter, DryRunResult, render_sci_svg
from .contracts import (
    DEFAULT_PROMPT_VERSION,
    AgentEvidence,
    ModelBatch,
    ModelOutput,
    TrackSpec,
)
from .foundation import (
    FOUNDATION_PROMPT_VERSION,
    FOUNDATION_SCHEMA_VERSION,
    ConditioningSpec,
    FoundationModelRef,
    FoundationTaskEnvelope,
    PromotionGate,
    TensorFieldSpec,
    VisibilityPolicy,
    load_foundation_routes,
)
from .foundation_prompts import (
    SUPERVISORY_RESPONSE_SCHEMA,
    SUPERVISORY_TEMPLATE_ID,
    SupervisoryPrompt,
    build_supervisory_prompt,
    invoke_supervisory_prompt,
    validate_supervisory_response,
)
from .controls import apply_control, counterfactual_control, random_control, real_control, shuffle_control
from .source_lock import (
    DEFAULT_SOURCE_MANIFEST,
    SourceFileRecord,
    SourceLockError,
    SourceManifest,
    SourceManifestStatus,
    verify_default_source_manifest,
)

__all__ = [
    "AgentEvidence",
    "AgentParseError",
    "AgentUnavailableError",
    "CacheCorruptionError",
    "DEFAULT_PROMPT_VERSION",
    "DEFAULT_SOURCE_MANIFEST",
    "DryRunResult",
    "FOUNDATION_PROMPT_VERSION",
    "FOUNDATION_SCHEMA_VERSION",
    "ConditioningSpec",
    "FoundationModelRef",
    "FoundationTaskEnvelope",
    "GaiaDAGTAdapter",
    "ModelBatch",
    "ModelOutput",
    "PromotionGate",
    "SourceFileRecord",
    "SourceLockError",
    "SourceManifest",
    "SourceManifestStatus",
    "SUPERVISORY_RESPONSE_SCHEMA",
    "SUPERVISORY_TEMPLATE_ID",
    "SupervisoryPrompt",
    "TrackSpec",
    "TensorFieldSpec",
    "VisibilityPolicy",
    "agent_unavailable",
    "apply_control",
    "counterfactual_control",
    "build_supervisory_prompt",
    "invoke_supervisory_prompt",
    "load_cached_agent_evidence",
    "load_foundation_routes",
    "parse_api_payload",
    "predictive_text_agent",
    "random_control",
    "real_control",
    "render_sci_svg",
    "require_api_key",
    "shuffle_control",
    "supervisory_qc_agent",
    "validate_supervisory_response",
    "verify_default_source_manifest",
]
